### ISSUE TITLE
Заодно поиграем в работу с багами на гитхабе. 

### ISSUE THREAD

**Issue by NikolayShubenkovProgSchool** [anatoliykant/QuizNew_Kant#1]
проект пустой, попробуйте разобраться, в чем дело.

Как разберетесь - пишите тут. я увижу ваш ответ и закрою эту задачу.

**Comment by anatoliykant** [comment]
Ок, посмотрю в чем дело 25.01.2016, 23:42, "Nik" <notifications@github.com>:проект пустой, попробуйте разобраться, в чем дело.Как разберетесь - пишите тут. я увижу ваш ответ и закрою эту задачу.—Reply to this email directly or view it on GitHub.￼
